### ISSUE TITLE
The default value of `persist-exports` not respected

### ISSUE THREAD

**Issue by CodeMan99** [postmanlabs/newman-orb#14]
## Orb version:

1.0.0

## What happened:

The default value (false) of `persist-exports` did not prevent `persist_workspace` from executing.

![image](https://user-images.githubusercontent.com/6373201/212389378-225bf012-875c-4e25-a423-6f685990c272.png)

## Expected behavior:

Only run `persist_workspace` if the `persist-exports` value is explicitly true.

## Additional Information:

Relevant snippet of my circleci config.

```
version: 2.1

orbs:
  newman: postman/newman@1.0.0

workflows:
  test:
    jobs:
      - newman/run:
          collection: https://api.getpostman.com/collections/${COLLECTION_ID}?apikey=$POSTMAN_API_KEY
          environment: https://api.getpostman.com/environments/${ENVIRONMENT_ID}?apikey=$POSTMAN_API_KEY
          timeout: "60000"
```
