### ISSUE TITLE
Unable to restore a cache

### ISSUE THREAD

**Issue by andrewpearce-digital** [postmanlabs/newman-orb#2]
To use the newman-orb in my CircleCI pipeline, I'm generating an environment file with AWS credentials and session tokens.

The environment file is created on a circleci/ruby executor, stored to cache and then restored to my newman-collection-run job.

```
...


jobs:
  build_api_test_file:
    executor: ruby
    steps:
      - checkout
      - run: generate_postman_environment.rb
      - save_cache:
          key: api_test_config-{{ .Branch }}-{{ .Revision }}
          paths: ./tests/generated.postman_environment.json
  newman-collection-run:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - restore_cache:
          keys:
            - api_test_config-{{ .Branch }}-{{ .Revision }}
      - newman/newman-run:
          collection: https://www.getpostman.com/collections/<id>
          environment: ./tests/generated.postman_environment.json
```

When I run my pipeline, I get to restore cache which returns this

```Skipping cache - error checking storage: RequestError: send request failed
caused by: Get https://xxxxxxxx.amazonaws.com/xxxxxxxxxxxxxxxxxx: 
x509: certificate signed by unknown authority
```

I think this can be fixed by adding ca-certificates to the docker image used as the executor for the orb.
https://support.circleci.com/hc/en-us/articles/360016505753-Resolve-Certificate-Signed-By-Unknown-Authority-error-in-Alpine-images
