### ISSUE TITLE
Example config not working, even not validate

### ISSUE THREAD

**Issue by kesamlats** [postmanlabs/newman-orb#6]
```
version: 2.1
orbs:
  newman: postman/newman@1.0.0
jobs:
  newman-collection-run:
    # use the official newman docker image via newman/postman-newman-docker executor
    executor: newman/postman-newman-docker
    
    steps:
      # checkout step is optional if you are not referencing any files from the project
      - checkout
      
      # use newman-run command
      - newman/newman-run:
          collection: ./collection.json
```
I had and issues with following example. Validation says that for version 1.0.0 there is no such orb. Worked only for 0.0.1 and 0.0.2.
After setting v0.0.2 it was saying that build job is not defined. Once I set the dummy build job it worked.

Can you pls fix examples both here and in circleci orb registry so it can be smoothly used even by people who has just few exp with circleci? Thank you
